<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.5.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>1c822c3a-4dd3-4ba7-ac71-df25a6b74631</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="13.0.2" />
    <PackageReference Include="Aspire.Hosting.Kafka" Version="13.0.2" />
    <PackageReference Include="Aspire.Hosting.MongoDB" Version="13.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hospital.Api.Host\Hospital.Api.Host.csproj" />
    <ProjectReference Include="..\Hospital.Generator.Kafka.Host\Hospital.Generator.Kafka.Host.csproj" />
  </ItemGroup>

</Project>
